# Generated by Django 5.2.6 on 2026-01-04 21:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_conn', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=90, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip', models.CharField(max_length=120, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='hub.cd')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='hub.cd')),
            ],
        ),
    ]
